version: '3.8'
services:
  jupyterlab:
    build: .
    image: ud-datascience
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '8888:8888'
    volumes:
      - ./.jupyter:/home/jovyan/.jupyter
      - ./:/home/jovyan/work
    command: start.sh jupyter lab --NotebookApp.token=''
